execute at @s positioned ~ ~ ~0 run function putting:place_redstone_block_for_0
execute at @s positioned ~ ~ ~2 run function putting:place_redstone_block_for_1
execute at @s positioned ~ ~ ~4 run function putting:place_redstone_block_for_2
execute at @s positioned ~ ~ ~6 run function putting:place_redstone_block_for_3
execute at @s positioned ~ ~ ~8 run function putting:place_redstone_block_for_4
execute at @s positioned ~ ~ ~10 run function putting:place_redstone_block_for_5
execute at @s positioned ~ ~ ~12 run function putting:place_redstone_block_for_6
execute at @s positioned ~ ~ ~14 run function putting:place_redstone_block_for_7
execute at @s positioned ~ ~ ~16 run function putting:place_redstone_block_for_8
execute at @s positioned ~ ~ ~18 run function putting:place_redstone_block_for_9
execute at @s positioned ~ ~ ~20 run function putting:place_redstone_block_for_upper_a
execute at @s positioned ~ ~ ~22 run function putting:place_redstone_block_for_upper_b
execute at @s positioned ~ ~ ~24 run function putting:place_redstone_block_for_upper_c
execute at @s positioned ~ ~ ~26 run function putting:place_redstone_block_for_upper_d
execute at @s positioned ~ ~ ~28 run function putting:place_redstone_block_for_upper_e
execute at @s positioned ~ ~ ~30 run function putting:place_redstone_block_for_upper_f
execute at @s positioned ~ ~ ~32 run function putting:place_redstone_block_for_upper_g
execute at @s positioned ~ ~ ~34 run function putting:place_redstone_block_for_upper_h
execute at @s positioned ~ ~ ~36 run function putting:place_redstone_block_for_upper_i
execute at @s positioned ~ ~ ~38 run function putting:place_redstone_block_for_upper_j
execute at @s positioned ~ ~ ~40 run function putting:place_redstone_block_for_upper_k
execute at @s positioned ~ ~ ~42 run function putting:place_redstone_block_for_upper_l
execute at @s positioned ~ ~ ~44 run function putting:place_redstone_block_for_upper_m
execute at @s positioned ~ ~ ~46 run function putting:place_redstone_block_for_upper_n
execute at @s positioned ~ ~ ~48 run function putting:place_redstone_block_for_upper_o
execute at @s positioned ~ ~ ~50 run function putting:place_redstone_block_for_upper_p
execute at @s positioned ~ ~ ~52 run function putting:place_redstone_block_for_upper_q
execute at @s positioned ~ ~ ~54 run function putting:place_redstone_block_for_upper_r
execute at @s positioned ~ ~ ~56 run function putting:place_redstone_block_for_upper_s
execute at @s positioned ~ ~ ~58 run function putting:place_redstone_block_for_upper_t
execute at @s positioned ~ ~ ~60 run function putting:place_redstone_block_for_upper_u
execute at @s positioned ~ ~ ~62 run function putting:place_redstone_block_for_upper_v
execute at @s positioned ~ ~ ~64 run function putting:place_redstone_block_for_upper_w
execute at @s positioned ~ ~ ~66 run function putting:place_redstone_block_for_upper_x
execute at @s positioned ~ ~ ~68 run function putting:place_redstone_block_for_upper_y
execute at @s positioned ~ ~ ~70 run function putting:place_redstone_block_for_upper_z
