# L
setblock ~0 ~1 ~ observer[facing=up]
setblock ~9 ~1 ~ observer[facing=up]
setblock ~18 ~1 ~ observer[facing=up]
setblock ~27 ~1 ~ observer[facing=up]
setblock ~36 ~1 ~ observer[facing=up]
setblock ~45 ~1 ~ observer[facing=up]
setblock ~54 ~1 ~ observer[facing=up]
setblock ~63 ~1 ~ observer[facing=up]
setblock ~64 ~1 ~ observer[facing=up]
setblock ~65 ~1 ~ observer[facing=up]
setblock ~66 ~1 ~ observer[facing=up]
setblock ~67 ~1 ~ observer[facing=up]
setblock ~68 ~1 ~ observer[facing=up]
setblock ~69 ~1 ~ observer[facing=up]
setblock ~70 ~1 ~ observer[facing=up]
