# Y
setblock ~0 ~1 ~ observer[facing=up]
setblock ~7 ~1 ~ observer[facing=up]
setblock ~10 ~1 ~ observer[facing=up]
setblock ~15 ~1 ~ observer[facing=up]
setblock ~20 ~1 ~ observer[facing=up]
setblock ~23 ~1 ~ observer[facing=up]
setblock ~30 ~1 ~ observer[facing=up]
setblock ~31 ~1 ~ observer[facing=up]
setblock ~39 ~1 ~ observer[facing=up]
setblock ~40 ~1 ~ observer[facing=up]
setblock ~48 ~1 ~ observer[facing=up]
setblock ~49 ~1 ~ observer[facing=up]
setblock ~57 ~1 ~ observer[facing=up]
setblock ~58 ~1 ~ observer[facing=up]
setblock ~66 ~1 ~ observer[facing=up]
setblock ~67 ~1 ~ observer[facing=up]
