# X
setblock ~0 ~1 ~ observer[facing=up]
setblock ~7 ~1 ~ observer[facing=up]
setblock ~10 ~1 ~ observer[facing=up]
setblock ~15 ~1 ~ observer[facing=up]
setblock ~20 ~1 ~ observer[facing=up]
setblock ~23 ~1 ~ observer[facing=up]
setblock ~30 ~1 ~ observer[facing=up]
setblock ~31 ~1 ~ observer[facing=up]
setblock ~39 ~1 ~ observer[facing=up]
setblock ~40 ~1 ~ observer[facing=up]
setblock ~47 ~1 ~ observer[facing=up]
setblock ~50 ~1 ~ observer[facing=up]
setblock ~55 ~1 ~ observer[facing=up]
setblock ~60 ~1 ~ observer[facing=up]
setblock ~63 ~1 ~ observer[facing=up]
setblock ~70 ~1 ~ observer[facing=up]
